services:
  - type: web
    name: allocgest-api
    runtime: python
    runtimeVersion: "3.12"
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r project_root/requirements.txt
      cd project_root && python manage.py collectstatic --noinput

    startCommand: |
      cd project_root && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DB_ENGINE
        value: django.db.backends.mysql
      - key: DB_PORT
        value: "3306"
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
