# Generated by Django 6.0.3 on 2026-06-24 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado para DESUP'), ('Aprovado', 'Aprovado pela DESUP')], default='Rascunho', max_length=20)),
                ('sei_numero', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='O formato do SEI deve ser SEI-999999/999999/9999', regex='^SEI-\\d{6}/\\d{6}/\\d{4}$')], verbose_name='Número SEI')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultimo_ajuste', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alocação Curricular',
                'verbose_name_plural': 'Alocações Curriculares',
                'ordering': ['-semestre', 'curso'],
            },
        ),
    ]
