# Generated by Django 6.0.3 on 2026-06-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocations', '0001_initial'),
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaocurricular',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseunit'),
        ),
        migrations.AddField(
            model_name='alocacaocurricular',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_consolidadas', to='core.unidade'),
        ),
        migrations.AlterUniqueTogether(
            name='alocacaocurricular',
            unique_together={('curso', 'semestre', 'turno')},
        ),
    ]
