# Generated by Django 6.0.3 on 2026-09-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alocacaocurricular',
            table='harpiadb_alocacoes_alocacao_curricular',
        ),
    ]
