# Generated by Django 6.0.3 on 2026-06-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Curso')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='courses.course', verbose_name='Curso')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='core.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Curso na Unidade',
                'verbose_name_plural': 'Cursos na Unidade',
                'ordering': ['curso__nome', 'unidade__nome'],
            },
        ),
        migrations.CreateModel(
            name='CurricularComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Componente Curricular')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Codigo')),
                ('carga_horaria_padrao', models.PositiveIntegerField(verbose_name='Carga Horária Padrão')),
                ('creditos', models.PositiveSmallIntegerField(default=0, verbose_name='Creditos')),
                ('ementa', models.TextField(blank=True, verbose_name='Ementa')),
                ('pre_requisitos', models.ManyToManyField(blank=True, related_name='componentes_dependentes', to='courses.curricularcomponent', verbose_name='Pre-requisitos padrao')),
            ],
            options={
                'verbose_name': 'Componente Curricular',
                'verbose_name_plural': 'Componentes Curriculares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', help_text='Ex: MC-ADS-2026', max_length=100, verbose_name='Código da Matriz')),
                ('is_vigente', models.BooleanField(default=True, help_text='Se True, esta é a matriz atual do curso.', verbose_name='Vigente')),
                ('is_rascunho', models.BooleanField(default=False, help_text='Se True, esta matriz ainda está em rascunho.', verbose_name='Rascunho')),
                ('criada_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criada em')),
                ('periodo_letivo', models.CharField(blank=True, help_text='Ex: 2026.1', max_length=20, null=True, verbose_name='Período Letivo')),
                ('turno', models.CharField(blank=True, choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, null=True, verbose_name='Turno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='courses.courseunit', verbose_name='Curso na Unidade')),
            ],
            options={
                'verbose_name': 'Matriz Curricular',
                'verbose_name_plural': 'Matrizes Curriculares',
                'ordering': ['curso'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_semestre', models.CharField(help_text='Ex: 2024.1, 2024.2', max_length=20, verbose_name='Ano/Semestre')),
                ('identificador', models.CharField(help_text='Ex: T01, A', max_length=50, verbose_name='Identificador da Turma')),
                ('matriz_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='courses.curriculummatrix', verbose_name='Matriz Curricular')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='MatrixComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Codigo na matriz')),
                ('periodo', models.CharField(blank=True, help_text='Ex: 1o periodo, 2o periodo', max_length=50, verbose_name='Periodo do componente')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horaria')),
                ('creditos', models.PositiveSmallIntegerField(default=0, verbose_name='Creditos')),
                ('compartilhado', models.BooleanField(default=False, verbose_name='Compartilhado com outro curso')),
                ('carga_horaria_semanal', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Carga horaria por semana')),
                ('distribuicao_semanal', models.TextField(blank=True, verbose_name='Distribuicao semanal')),
                ('status', models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Incompleto'), ('SEM_PROFESSOR', 'Sem professor'), ('NAO_OFERECIDA', 'Nao oferecida')], default='SEM_PROFESSOR', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('componente_curricular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_matriz', to='courses.curricularcomponent', verbose_name='Componente Curricular')),
                ('curso_compartilhado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes_compartilhados', to='courses.courseunit', verbose_name='Curso compartilhado')),
            ],
            options={
                'verbose_name': 'Componente da Matriz',
                'verbose_name_plural': 'Componentes da Matriz',
                'ordering': ['matriz', 'periodo', 'componente_curricular__nome'],
            },
        ),
    ]
