# Generated by Django 6.0.3 on 2026-06-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixcomponent',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes_matriz', to='professors.professor', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='matrixcomponent',
            name='matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_da_matriz', to='courses.curriculummatrix', verbose_name='Matriz Curricular'),
        ),
        migrations.AddField(
            model_name='matrixcomponent',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, related_name='requisito_em_matrizes', to='courses.curricularcomponent', verbose_name='Pre-requisitos'),
        ),
        migrations.AddField(
            model_name='curriculummatrix',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='matrizes', through='courses.MatrixComponent', to='courses.curricularcomponent', verbose_name='Componentes Curriculares'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='matriz_componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='courses.matrixcomponent', verbose_name='Componente da Matriz'),
        ),
        migrations.AlterUniqueTogether(
            name='courseunit',
            unique_together={('curso', 'unidade')},
        ),
        migrations.AlterUniqueTogether(
            name='matrixcomponent',
            unique_together={('matriz', 'componente_curricular')},
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('matriz_curricular', 'ano_semestre', 'identificador')},
        ),
    ]
