# Generated by Django 6.0.3 on 2026-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_matrix_multi_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculummatrix',
            options={'ordering': ['curso__nome', 'nome'], 'verbose_name': 'Matriz Curricular', 'verbose_name_plural': 'Matrizes Curriculares'},
        ),
        migrations.AddField(
            model_name='curricularcomponent',
            name='obrigatoria',
            field=models.BooleanField(default=True, verbose_name='Obrigatória'),
        ),
    ]
