# Generated by Django 6.0.3 on 2026-07-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_curriculummatrix_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curricularcomponent',
            name='sigla',
        ),
    ]
