# Generated by Django 6.0.3 on 2026-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tables_harpiadb_prefix'),
        ('courses', '0005_remove_curricularcomponent_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curricularcomponent',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, db_table='harpiadb_cursos_componente_pre_requisitos', related_name='componentes_dependentes', to='courses.curricularcomponent', verbose_name='Pre-requisitos padrao'),
        ),
        migrations.AlterField(
            model_name='curriculummatrix',
            name='unidades',
            field=models.ManyToManyField(blank=True, db_table='harpiadb_cursos_matriz_unidades', related_name='curriculum_matrices', to='core.unidade', verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='matrixcomponent',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, db_table='harpiadb_cursos_matriz_pre_requisitos', related_name='requisito_em_matrizes', to='courses.curricularcomponent', verbose_name='Pre-requisitos'),
        ),
        migrations.AlterModelTable(
            name='classgroup',
            table='harpiadb_cursos_turma',
        ),
        migrations.AlterModelTable(
            name='course',
            table='harpiadb_cursos_curso',
        ),
        migrations.AlterModelTable(
            name='courseunit',
            table='harpiadb_cursos_curso_unidade',
        ),
        migrations.AlterModelTable(
            name='curricularcomponent',
            table='harpiadb_cursos_componente_curricular',
        ),
        migrations.AlterModelTable(
            name='curriculummatrix',
            table='harpiadb_cursos_matriz_curricular',
        ),
        migrations.AlterModelTable(
            name='matrixcomponent',
            table='harpiadb_cursos_componente_matriz',
        ),
    ]
