# Generated by Django 6.0.3 on 2026-06-24 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('professors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(help_text='Ex: 2026.1', max_length=10, verbose_name='Semestre')),
                ('sei_numero', models.CharField(blank=True, help_text='Formato: SEI-999999/999999/9999', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='O formato do SEI deve ser SEI-999999/999999/9999', regex='^SEI-\\d{6}/\\d{6}/\\d{4}$')], verbose_name='Número SEI')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado para DESUP'), ('APROVADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('motivo_status_desup', models.TextField(blank=True, verbose_name='Motivo da decisao DESUP')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_extra', to='professors.professor', verbose_name='Docente')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias_extra', to='core.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Pendência Extracurricular',
                'verbose_name_plural': 'Pendências Extracurriculares',
                'ordering': ['-semestre', 'professor__rh_nome'],
                'unique_together': {('professor', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='OrientacaoTCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_orientandos', models.PositiveSmallIntegerField(help_text='Máximo de 8 orientandos por professor.', validators=[django.core.validators.MaxValueValidator(8)], verbose_name='Nº de Orientandos')),
                ('num_orientandos_aprovados', models.PositiveSmallIntegerField(blank=True, help_text='Nº de orientandos aprovados pela DESUP. Se vazio, usa o total solicitado.', null=True, validators=[django.core.validators.MaxValueValidator(8)], verbose_name='Orientandos Aprovados')),
                ('carga_horaria', models.DecimalField(decimal_places=1, editable=False, help_text='Calculado automaticamente: orientandos × 0,5 (máx 4h).', max_digits=4, verbose_name='Carga Horária (h)')),
                ('horas_aprovadas', models.DecimalField(blank=True, decimal_places=1, help_text='Valor definido pela DESUP. Se vazio, usa o valor calculado.', max_digits=4, null=True, verbose_name='Horas Aprovadas (DESUP)')),
                ('parecer_desup', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=20, verbose_name='Parecer DESUP')),
                ('motivo_parecer', models.TextField(blank=True, verbose_name='Motivo do Parecer')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes_tcc', to='extra_curricular.pendenciaextra', verbose_name='Pendência')),
            ],
            options={
                'verbose_name': 'Orientação de TCC',
                'verbose_name_plural': 'Orientações de TCC',
            },
        ),
        migrations.CreateModel(
            name='AtividadeExtensionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_estudantes', models.PositiveIntegerField(verbose_name='Nº de Estudantes')),
                ('num_estudantes_aprovados', models.PositiveIntegerField(blank=True, help_text='Nº de estudantes aprovados pela DESUP. Se vazio, usa o total solicitado.', null=True, verbose_name='Estudantes Aprovados')),
                ('carga_horaria', models.DecimalField(decimal_places=1, editable=False, help_text='Calculado automaticamente: estudantes × 0,5.', max_digits=6, verbose_name='Carga Horária (h)')),
                ('horas_aprovadas', models.DecimalField(blank=True, decimal_places=1, help_text='Valor definido pela DESUP. Se vazio, usa o valor calculado.', max_digits=6, null=True, verbose_name='Horas Aprovadas (DESUP)')),
                ('parecer_desup', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=20, verbose_name='Parecer DESUP')),
                ('motivo_parecer', models.TextField(blank=True, verbose_name='Motivo do Parecer')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_extensao', to='extra_curricular.pendenciaextra', verbose_name='Pendência')),
            ],
            options={
                'verbose_name': 'Atividade Extensionista',
                'verbose_name_plural': 'Atividades Extensionistas',
            },
        ),
        migrations.CreateModel(
            name='ReducaoCargaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_reducao', models.TextField(help_text='Descreva a legislação ou aprovação que fundamenta a redução.', verbose_name='Motivo da Redução')),
                ('horas_reduzidas', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Horas de Aula Reduzidas')),
                ('horas_aprovadas', models.DecimalField(blank=True, decimal_places=1, help_text='Valor definido pela DESUP. Se vazio, usa o valor solicitado.', max_digits=5, null=True, verbose_name='Horas Aprovadas (DESUP)')),
                ('parecer_desup', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=20, verbose_name='Parecer DESUP')),
                ('motivo_parecer', models.TextField(blank=True, verbose_name='Motivo do Parecer')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reducoes_ch', to='extra_curricular.pendenciaextra', verbose_name='Pendência')),
            ],
            options={
                'verbose_name': 'Redução de Carga Horária',
                'verbose_name_plural': 'Reduções de Carga Horária',
            },
        ),
    ]
