# Generated by Django 6.0.3 on 2026-07-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_curricular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeextensionista',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Se True, a unidade não pode mais editar/excluir este item (já enviado em definitivo).', verbose_name='Bloqueado (enviado à DESUP)'),
        ),
        migrations.AddField(
            model_name='orientacaotcc',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Se True, a unidade não pode mais editar/excluir este item (já enviado em definitivo).', verbose_name='Bloqueado (enviado à DESUP)'),
        ),
        migrations.AddField(
            model_name='reducaocargahoraria',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Se True, a unidade não pode mais editar/excluir este item (já enviado em definitivo).', verbose_name='Bloqueado (enviado à DESUP)'),
        ),
    ]
