# Generated by Django 6.0.3 on 2026-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_curricular', '0002_atividadeextensionista_bloqueado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeextensionista',
            name='parecer_desup',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('INDEFERIDO', 'Indeferido')], default='PENDENTE', max_length=20, verbose_name='Parecer DESUP'),
        ),
        migrations.AlterField(
            model_name='orientacaotcc',
            name='parecer_desup',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('INDEFERIDO', 'Indeferido')], default='PENDENTE', max_length=20, verbose_name='Parecer DESUP'),
        ),
        migrations.AlterField(
            model_name='pendenciaextra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado para DESUP'), ('APROVADO', 'Finalizado'), ('INDEFERIDO', 'Indeferido')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reducaocargahoraria',
            name='parecer_desup',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('INDEFERIDO', 'Indeferido')], default='PENDENTE', max_length=20, verbose_name='Parecer DESUP'),
        ),
    ]
