# Generated by Django 6.0.3 on 2026-08-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_curricular', '0003_alter_atividadeextensionista_parecer_desup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciaextra',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado para DESUP'), ('APROVADO', 'Finalizado'), ('PARCIAL', 'Finalizado parcialmente'), ('INDEFERIDO', 'Indeferido')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
    ]
