# Generated by Django 6.0.3 on 2026-09-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_curricular', '0004_alter_pendenciaextra_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atividadeextensionista',
            table='harpiadb_extracurricular_atividade_extensionista',
        ),
        migrations.AlterModelTable(
            name='orientacaotcc',
            table='harpiadb_extracurricular_orientacao_tcc',
        ),
        migrations.AlterModelTable(
            name='pendenciaextra',
            table='harpiadb_extracurricular_pendencia',
        ),
        migrations.AlterModelTable(
            name='reducaocargahoraria',
            table='harpiadb_extracurricular_reducao_carga_horaria',
        ),
    ]
