# Generated by Django 6.0.3 on 2026-09-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atalhodashboard'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atalhodashboard',
            table='harpiadb_nucleo_atalho_dashboard',
        ),
        migrations.AlterModelTable(
            name='auditoriaglobal',
            table='harpiadb_nucleo_auditoria',
        ),
        migrations.AlterModelTable(
            name='janelaentrega',
            table='harpiadb_nucleo_janela_entrega',
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table='harpiadb_nucleo_notificacao',
        ),
        migrations.AlterModelTable(
            name='unidade',
            table='harpiadb_nucleo_unidade',
        ),
    ]
