# Generated by Django 6.0.3 on 2026-10-01 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tables_harpiadb_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do usuário')),
                ('perfil_usuario', models.CharField(blank=True, max_length=30, verbose_name='Perfil')),
                ('unidade_usuario', models.CharField(blank=True, max_length=255, verbose_name='Unidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data')),
                ('metodo', models.CharField(max_length=10, verbose_name='Método HTTP')),
                ('caminho', models.CharField(db_index=True, max_length=500, verbose_name='Caminho')),
                ('status_http', models.PositiveSmallIntegerField(db_index=True, verbose_name='Status HTTP')),
                ('tipo_erro', models.CharField(db_index=True, max_length=255, verbose_name='Tipo do erro')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador/User-Agent')),
                ('request_id', models.CharField(db_index=True, max_length=32, verbose_name='ID da requisição')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Fingerprint')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_sistema', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Erro do Sistema',
                'verbose_name_plural': 'Erros do Sistema',
                'db_table': 'harpiadb_nucleo_erro_sistema',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status_http', 'criado_em'], name='harpia_erro_status_data_idx')],
            },
        ),
    ]
