# Generated by Django 6.0.3 on 2026-06-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Ensino Superior, BTT', max_length=100, verbose_name='Nome do Contrato')),
                ('categoria', models.CharField(choices=[('TERCEIRIZADO', 'Terceirizado'), ('EFETIVO', 'Efetivo'), ('CONCURSADO', 'Concursado')], default='EFETIVO', max_length=20, verbose_name='Categoria do Contrato')),
                ('regime_trabalho', models.CharField(default='', help_text='Ex: 40h DE, 20h', max_length=20, verbose_name='Regime de Trabalho')),
                ('dias_presenca_obrigatorios', models.PositiveSmallIntegerField(default=3, help_text='Quantidade mínima de dias na unidade (ex.: 40h semanais → 3 dias). Definido pela DESUP.', verbose_name='Dias de presença obrigatórios')),
                ('max_class_hours', models.PositiveIntegerField(verbose_name='Limite de horas em sala')),
                ('max_total_hours', models.PositiveIntegerField(default=40, help_text='Teto global (ex: 40h)', verbose_name='Limite total de horas')),
                ('max_classes', models.PositiveIntegerField(verbose_name='Limite de turmas')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_funcional', models.CharField(db_column='ID_FUNCIONAL', db_index=True, max_length=50, unique=True, verbose_name='ID Funcional')),
                ('rh_matricula', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Matrícula RH')),
                ('rh_nome', models.CharField(max_length=255, verbose_name='Nome (RH)')),
                ('rh_email', models.EmailField(max_length=254, verbose_name='E-mail (RH)')),
                ('desup_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome (Ajuste DESUP)')),
                ('desup_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail (Ajuste DESUP)')),
                ('is_cedido', models.BooleanField(default=False, help_text='Tratado como carência se True.', verbose_name='Professor Cedido (Regra #4)')),
                ('ha', models.PositiveIntegerField(default=0, help_text='Horas-aula semanais do professor', verbose_name='HA (Horas-Aula)')),
                ('materia', models.CharField(blank=True, choices=[('INFO', 'Informática (Computação)'), ('ELETRO', 'Eletrotécnica (Eletrônica)'), ('MECANICA', 'Mecânica (Automação)'), ('EDIFICACOES', 'Edificações (Civil)'), ('ADMIN', 'Administração (Gestão)'), ('SAUDE', 'Saúde (Enfermagem)'), ('DESIGN', 'Design (Moda)'), ('TELECOM', 'Telecomunicações'), ('QUIMICA', 'Química (Meio Ambiente)'), ('TURISMO', 'Turismo (Hospitalidade)'), ('FORMACAO', 'Formação Geral'), ('OUTROS', 'Outros')], default='', help_text='Área de atuação do professor (ex: Informática, Saúde, etc.)', max_length=20, verbose_name='Eixo')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Afastado', 'Ausente/Afastado')], default='Ativo', max_length=20, verbose_name='Status')),
                ('cursos', models.ManyToManyField(blank=True, related_name='professores_cursos', to='courses.course', verbose_name='Cursos')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professores', to='professors.contracttype', verbose_name='Tipo de Contrato')),
                ('unidade_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='core.unidade', verbose_name='Unidade Principal')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['rh_nome'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='ausencias/%Y/%m/', verbose_name='Atestado/Comprovante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='professors.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Registro de Ausência',
                'verbose_name_plural': 'Registros de Ausência',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(2, 'Segunda-feira'), (3, 'Terça-feira'), (4, 'Quarta-feira'), (5, 'Quinta-feira'), (6, 'Sexta-feira'), (7, 'Sábado'), (1, 'Domingo')], verbose_name='Dia da Semana')),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1, verbose_name='Turno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='professors.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['professor', 'dia_semana', 'turno'],
                'unique_together': {('professor', 'dia_semana', 'turno')},
            },
        ),
    ]
