# Generated by Django 6.0.3 on 2026-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_tables_harpiadb_prefix'),
        ('professors', '0005_remove_limite_horas_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cursos',
            field=models.ManyToManyField(blank=True, db_table='harpiadb_professores_professor_cursos', related_name='professores_cursos', to='courses.course', verbose_name='Cursos'),
        ),
        migrations.AlterModelTable(
            name='absencerecord',
            table='harpiadb_professores_ausencia',
        ),
        migrations.AlterModelTable(
            name='availability',
            table='harpiadb_professores_disponibilidade',
        ),
        migrations.AlterModelTable(
            name='contracttype',
            table='harpiadb_professores_tipo_contrato',
        ),
        migrations.AlterModelTable(
            name='professor',
            table='harpiadb_professores_professor',
        ),
    ]
