# Generated by Django 6.0.3 on 2026-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_professor_matricula_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='carga_diferenciada',
            field=models.BooleanField(default=False, help_text='Marque quando a carga horária deste professor não é a do tipo de contrato.', verbose_name='Professor com carga diferente'),
        ),
        migrations.AddField(
            model_name='professor',
            name='carga_horaria_personalizada',
            field=models.PositiveIntegerField(blank=True, help_text='Carga semanal total. A alocação em sala é metade (20h → 10h; 40h → 20h).', null=True, verbose_name='Carga horária total (h)'),
        ),
    ]
