# Generated by Django 6.0.3 on 2026-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Administrador (TI DESUP)'), ('DESUP', 'Coordenador DESUP'), ('COORDENADOR_UNIDADE', 'Coordenador de Unidade')], default='COORDENADOR_UNIDADE', max_length=30, verbose_name='Perfil de Acesso'),
        ),
    ]
