# Generated by Django 6.0.3 on 2026-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_perfil'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='harpiadb_contas_usuario_grupos', help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='harpiadb_contas_usuario_permissoes', help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='passwordresetrequest',
            table='harpiadb_contas_redefinicao_senha',
        ),
        migrations.AlterModelTable(
            name='selfpasswordchangerequest',
            table='harpiadb_contas_alteracao_senha',
        ),
        migrations.AlterModelTable(
            name='user',
            table='harpiadb_contas_usuario',
        ),
    ]
