# Generated by Django 6.0.3 on 2026-10-01 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_tables_harpiadb_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expira_em', models.DateTimeField(db_index=True)),
                ('usado', models.BooleanField(db_index=True, default=False)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('solicitado_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_resets_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de redefinição por e-mail',
                'verbose_name_plural': 'Tokens de redefinição por e-mail',
                'db_table': 'harpiadb_contas_token_redefinicao_email',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['user', 'usado', 'criado_em'], name='harpia_reset_user_status_idx')],
            },
        ),
    ]
